# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 11

on:
  workflow_dispatch:
  schedule:
     - cron: '50  0-16 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    env:
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}


    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update

      - name: '运行 【11】'
        run: |
          cd ~/Scripts
          node Task/youth.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
