name: zqfx

on:
    workflow_dispatch:
    schedule:
        - cron: "32 0-16 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: zqfx

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: 'Install requests'
              run: |
                pip3 install requests
                pip3 install json
                pip3 install random,string
                npm install util
            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 喜马拉雅极速版"
              run: python3 Task/zqfx.py
